import { StyleSheet, Dimensions } from 'react-native';

  const { width, height } = Dimensions.get('window');



const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#F9FAFB',
    },
    header: {
      backgroundColor: '#10B981',
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 30,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
    },
    headerTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 24,
    },
    title: {
      fontSize: 28,
      fontWeight: '700',
      color: '#FFFFFF',
      letterSpacing: -0.5,
    },
    subtitle: {
      fontSize: 14,
      color: 'rgba(255, 255, 255, 0.8)',
      marginTop: 2,
      fontWeight: '400',
    },
    analyticsButton: {
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      borderRadius: 12,
      width: 44,
      height: 44,
      justifyContent: 'center',
      alignItems: 'center',
    },
    analyticsButtonText: {
      fontSize: 20,
    },
    totalContainer: {
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      padding: 20,
      borderRadius: 16,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    totalLabel: {
      fontSize: 14,
      color: 'rgba(255, 255, 255, 0.8)',
      fontWeight: '500',
      marginBottom: 4,
    },
    totalAmount: {
      fontSize: 32,
      fontWeight: '800',
      color: '#FFFFFF',
      letterSpacing: -1,
    },
    totalSubtext: {
      fontSize: 13,
      color: 'rgba(255, 255, 255, 0.7)',
      marginTop: 4,
      fontWeight: '400',
    },
    quickStats: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      marginTop: -20,
      marginBottom: 20,
    },
    statCard: {
      backgroundColor: '#FFFFFF',
      flex: 1,
      marginHorizontal: 4,
      padding: 16,
      borderRadius: 12,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
    statValue: {
      fontSize: 18,
      fontWeight: '700',
      color: '#111827',
      marginBottom: 2,
    },
    statLabel: {
      fontSize: 12,
      color: '#6B7280',
      fontWeight: '500',
    },
    formContainer: {
      backgroundColor: '#FFFFFF',
      margin: 20,
      padding: 24,
      borderRadius: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 5,
    },
    formTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#111827',
      marginBottom: 20,
      textAlign: 'center',
    },
    inputRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 20,
    },
    inputContainer: {
      flex: 0.48,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: '#374151',
      marginBottom: 8,
    },
    input: {
      borderWidth: 1,
      borderColor: '#E5E7EB',
      borderRadius: 12,
      padding: 16,
      backgroundColor: '#FFFFFF',
      fontSize: 16,
      color: '#111827',
    },
    sectionLabel: {
      fontSize: 16,
      fontWeight: '600',
      color: '#374151',
      marginBottom: 12,
    },
    categorySelectorContainer: {
      marginBottom: 24,
    },
    categorySelector: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 12,
      marginRight: 12,
      minWidth: 130,
      borderWidth: 1,
    },
    categorySelectorIcon: {
      fontSize: 16,
      marginRight: 8,
    },
    categorySelectorText: {
      fontSize: 13,
      fontWeight: '600',
    },
    addButton: {
      backgroundColor: '#10B981',
      borderRadius: 16,
      padding: 18,
      alignItems: 'center',
      shadowColor: '#10B981',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    },
    addButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
    },
    disabledButton: {
      opacity: 0.6,
    },
    quickActions: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingHorizontal: 20,
      marginBottom: 20,
    },
    quickAction: {
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      paddingVertical: 16,
      paddingHorizontal: 20,
      borderRadius: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
      minWidth: 90,
    },
    quickActionIcon: {
      marginBottom: 8,
    },
    quickActionEmoji: {
      fontSize: 24,
    },
    quickActionText: {
      fontSize: 12,
      color: '#6B7280',
      fontWeight: '600',
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      marginHorizontal: 20,
      marginBottom: 20,
      borderRadius: 16,
      paddingHorizontal: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
    searchIcon: {
      fontSize: 16,
      marginRight: 12,
      color: '#9CA3AF',
    },
    searchInput: {
      flex: 1,
      padding: 16,
      fontSize: 16,
      color: '#111827',
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      marginBottom: 16,
    },
    sectionHeaderTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: '#111827',
    },
    sectionHeaderCount: {
      fontSize: 14,
      color: '#6B7280',
      fontWeight: '500',
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 60,
    },
    loadingText: {
      marginTop: 16,
      fontSize: 16,
      color: '#6B7280',
      fontWeight: '500',
    },
    listContent: {
      paddingBottom: 20,
    },
    expenseItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: 16,
      marginHorizontal: 20,
      marginBottom: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
    expenseLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    categoryIcon: {
      width: 48,
      height: 48,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
    },
    categoryEmoji: {
      fontSize: 20,
    },
    expenseInfo: {
      flex: 1,
    },
    expenseDesc: {
      fontSize: 16,
      fontWeight: '600',
      color: '#111827',
      marginBottom: 4,
    },
    expenseCategory: {
      fontSize: 13,
      color: '#6B7280',
      marginBottom: 2,
      fontWeight: '500',
    },
    expenseDate: {
      fontSize: 12,
      color: '#9CA3AF',
      fontWeight: '400',
    },
    expenseRight: {
      alignItems: 'flex-end',
    },
    expenseAmount: {
      fontSize: 18,
      fontWeight: '700',
      color: '#EF4444',
      marginBottom: 8,
    },
    actionButtons: {
      flexDirection: 'row',
      gap: 8,
    },
    editButton: {
      backgroundColor: '#DBEAFE',
      borderRadius: 8,
      width: 32,
      height: 32,
      justifyContent: 'center',
      alignItems: 'center',
    },
    editButtonText: {
      fontSize: 14,
    },
    deleteButton: {
      backgroundColor: '#FEE2E2',
      borderRadius: 8,
      width: 32,
      height: 32,
      justifyContent: 'center',
      alignItems: 'center',
    },
    deleteButtonText: {
      fontSize: 14,
    },
    emptyContainer: {
      alignItems: 'center',
      paddingVertical: 60,
      paddingHorizontal: 40,
    },
    emptyEmoji: {
      fontSize: 64,
      marginBottom: 16,
    },
    emptyText: {
      fontSize: 20,
      color: '#6B7280',
      fontWeight: '600',
      marginBottom: 8,
      textAlign: 'center',
    },
    emptySubtext: {
      fontSize: 14,
      color: '#9CA3AF',
      textAlign: 'center',
      lineHeight: 20,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContainer: {
      backgroundColor: '#FFFFFF',
      borderRadius: 24,
      padding: 24,
      width: width * 0.9,
      maxWidth: 400,
      maxHeight: height * 0.8,
    },
    analyticsModalContainer: {
      maxHeight: height * 0.85,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: '#111827',
    },
    closeButton: {
      backgroundColor: '#F3F4F6',
      borderRadius: 12,
      width: 32,
      height: 32,
      justifyContent: 'center',
      alignItems: 'center',
    },
    closeButtonText: {
      fontSize: 16,
      color: '#6B7280',
      fontWeight: '600',
    },
    modalLabel: {
      fontSize: 16,
      fontWeight: '600',
      color: '#374151',
      marginBottom: 12,
      marginTop: 16,
    },
    modalInputContainer: {
      marginBottom: 16,
    },
    modalInputLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: '#374151',
      marginBottom: 8,
    },
    modalInput: {
      borderWidth: 1,
      borderColor: '#E5E7EB',
      borderRadius: 12,
      padding: 16,
      fontSize: 16,
      backgroundColor: '#FFFFFF',
      color: '#111827',
    },
    periodSelector: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      marginBottom: 24,
    },
    periodOption: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 12,
      minWidth: 90,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#E5E7EB',
    },
    periodOptionText: {
      fontSize: 14,
      fontWeight: '600',
    },
    filterOptions: {
      marginBottom: 20,
    },
    filterOption: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 12,
      marginRight: 12,
      minWidth: 110,
      borderWidth: 1,
      borderColor: '#E5E7EB',
    },
    filterOptionIcon: {
      fontSize: 14,
      marginRight: 8,
    },
    filterOptionText: {
      fontSize: 13,
      fontWeight: '600',
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 16,
      marginTop: 24,
    },
    cancelButton: {
      flex: 1,
      backgroundColor: '#F3F4F6',
      borderRadius: 12,
      padding: 16,
      alignItems: 'center',
    },
    cancelButtonText: {
      color: '#6B7280',
      fontSize: 16,
      fontWeight: '600',
    },
    updateButton: {
      flex: 1,
      backgroundColor: '#10B981',
      borderRadius: 12,
      padding: 16,
      alignItems: 'center',
    },
    updateButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
    },
    analyticsContainer: {
      flex: 1,
    },
    analyticsTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#111827',
      marginBottom: 20,
      textAlign: 'center',
    },
    overviewCards: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 24,
    },
    overviewCard: {
      flex: 1,
      backgroundColor: '#F9FAFB',
      borderRadius: 12,
      padding: 16,
      alignItems: 'center',
      marginHorizontal: 4,
      borderWidth: 1,
      borderColor: '#E5E7EB',
    },
    overviewCardTitle: {
      fontSize: 12,
      color: '#6B7280',
      marginBottom: 6,
      fontWeight: '500',
    },
    overviewCardAmount: {
      fontSize: 18,
      fontWeight: '700',
      color: '#10B981',
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: '#374151',
      marginBottom: 16,
    },
    categoryBreakdown: {
      backgroundColor: '#F9FAFB',
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: '#E5E7EB',
    },
    categoryBreakdownHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    categoryBreakdownLeft: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    categoryBreakdownIcon: {
      fontSize: 16,
      marginRight: 12,
    },
    categoryBreakdownName: {
      fontSize: 14,
      color: '#111827',
      fontWeight: '600',
    },
    categoryBreakdownAmount: {
      fontSize: 16,
      fontWeight: '700',
      color: '#10B981',
    },
    budgetProgress: {
      marginTop: 8,
    },
    budgetProgressBg: {
      backgroundColor: '#E5E7EB',
      borderRadius: 6,
      height: 6,
      marginBottom: 6,
    },
    budgetProgressFill: {
      height: 6,
      borderRadius: 6,
    },
    budgetProgressText: {
      fontSize: 11,
      fontWeight: '500',
    },
    
  });

  export default styles;
